services:
  - type: web
    name: amazon-package-dashboard
    env: python
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: PATH
        value: /opt/render/project/.venv/bin:$PATH