services:
  - type: web
    name: amazon-package-dashboard
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: PORT
        value: 10000
    healthCheckPath: /